#!/bin/bash
# Compile latex and bibtex

FILE_NAME="Gradu"

FILEIN=${FILE_NAME}".tex"

echo "================================================="
echo " Compiling '"$FILEIN"' using:"
echo " latex -> bibtext -> latex -> latex -> dvipdf"
echo "================================================="

rm build/*
rm $FILE_NAME.pdf

pdflatex --output-directory build $FILEIN

cd build
bibtex $FILE_NAME".aux"  #—output-directory=build $FILE_NAME.aux
makeindex $FILE_NAME".nlo" -s nomencl".ist" -o $FILE_NAME".nls"
#makeindex build/$FILE_NAME".nlo" -s build/nomencl".ist" -o build/$FILE_NAME".nls"
cd ..

pdflatex --output-directory build $FILEIN
pdflatex --output-directory build $FILEIN

#dvipdf $FILEIN

# Move pdf out of build directory
cp build/$FILE_NAME.pdf .

#check current OS & view pdf using appropriate method
viewPDF=1
if [ $viewPDF -eq 1 ]; then
#   unamestr=`uname`
#   if [ "$unamestr" == 'Linux' ]; then
       evince ${FILE_NAME}".pdf"
#   elif [ "$unamestr" == 'Darwin' ]; then
#       open -a /Applications/Preview.app build/${FILE_NAME}".pdf"
#   fi
fi

